/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Header: typeof import('./src/components/Layouts/Header.vue')['default']
    Layouts: typeof import('./src/components/Layouts/index.vue')['default']
    MenuContent: typeof import('./src/components/Layouts/MenuContent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideNav: typeof import('./src/components/Layouts/SideNav.vue')['default']
    TAside: typeof import('tdesign-vue-next/esm')['Aside']
    TBreadcrumb: typeof import('tdesign-vue-next/esm')['Breadcrumb']
    TButton: typeof import('tdesign-vue-next/esm')['Button']
    TContent: typeof import('tdesign-vue-next/esm')['Content']
    THeader: typeof import('tdesign-vue-next/esm')['Header']
    THeadMenu: typeof import('tdesign-vue-next/esm')['HeadMenu']
    TIcon: typeof import('tdesign-vue-next/esm')['Icon']
    TLayout: typeof import('tdesign-vue-next/esm')['Layout']
    TMenu: typeof import('tdesign-vue-next/esm')['Menu']
    TMenuItem: typeof import('tdesign-vue-next/esm')['MenuItem']
    TRadioGroup: typeof import('tdesign-vue-next/esm')['RadioGroup']
    TSpace: typeof import('tdesign-vue-next/esm')['Space']
    TSubmenu: typeof import('tdesign-vue-next/esm')['Submenu']
    TTree: typeof import('tdesign-vue-next/esm')['Tree']
  }
}
